host: 195.26.178.77
port: 9200
logFile: main.log
index: movies
types:
    - image
indexedFields:
    - Author
    - Source
    - SourceUrl
    - Title
    - Keywords
    - Description
indexedAlias:
    Author:
      - Creator
      - Author
      - SourceText
    Title:
      - Title
      - Keywords
indexedAliasNotFound:
    Author:
      - Автор не известен
    Title:
      - ""

dbHost:
dbName:
dbUser:
dbPass:

ST_WAIT_FOR_IDX: 0
ST_INDEXED: 1
ST_WAIT_FOR_RMV: 2
ST_WAIT_FOR_UPD: 3
ST_REMOVED: 4
