host: 195.26.178.77
port: 9200
logFile: main.log
index: movies
indexedFields:
    - Author
    - Source
    - SourceUrl
    - Title
indexStatus:
    - WAIT_FOR_IDX: 0
    - INDEXED: 1
    - WAIT_FOR_RMV: 2
    - WAIT_FOR_UPD: 3
    - REMOVED: 4
